title: Goblin Node Legal
description: Privacy Policy and Support for Goblin Node
theme: minima
url: "https://rainerweston.github.io"
baseurl: "/goblin-node-legal"

markdown: kramdown
plugins:
  - jekyll-feed
